language: php
php:
#  - '5.3'
#  - '5.4'
  - '5.5'
#  - '5.6'
#  - '7.0'
#  - hhvm
#  - nightly
before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --no-install-recommends redis-server
  - composer install

before_script:
  - ./tests/integration/start-services.sh

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --bootstrap ./tests/bootstrap.php
  - ./vendor/bin/phpunit -c ./phpunit.int.xml --bootstrap ./tests/bootstrap.int.php
